### ISSUE TITLE
Working with 'constant_memory'?

### ISSUE THREAD

**Issue by TheGodJulianos** [jmcnamara/xlsxwriter.lua#21]
I want to generate an excel sheet with ~20.000 rows and 74 columns.
I took a look into the documentation "Working with Memory and Performance" and after reading in approximately 35 different forums, I have no idea how to use

`for row in range(0, row_max):`
`for col in range(0, col_max):`
`worksheet.write(row, col, some_data)`

What is "some_data"?

A list (of all values in the table) (1)? A list of all rows (as lists) (1)? A tuple of lists (1)? Or a special command (2)? How do I grab the inside of the cell of the specific number of the row and column at this point of the code? It is sadly not even slightly explained in the documentation.

(1) does not work
(2) no idea what command

**Comment by moteus** [comment]
This is Lua library to only write data. You can not read any info from excel document.
From doc
```Lua
local Workbook = require "xlsxwriter.workbook"

local filename = "test.xlsx"

local workbook = Workbook:new(filename, {constant_memory = true})
local worksheet = workbook:add_worksheet()

for row = 0, 1000 do
  for col = 0, 10 do
    local data = string.format("%d - %d", row, col)
    worksheet:write(row, col, data)
  end
end

workbook:close()
```

**Comment by TheGodJulianos** [comment]
Oh, right, I did not recognize it! Sorry :D
