### ISSUE TITLE
Problem with Packager

### ISSUE THREAD

**Issue by 1linux** [jmcnamara/xlsxwriter.lua#25]
On Windows, starting with Win Vista, we found a privilege problem. Packager:_add_to_zip() uses the function "io.tmpfile()", which, in turn, uses the C-runtime function "tmpfile()". In Windows MSVCRT this ist defined as "create a temporary file on the root of the filesystem". Sadly most often this means, create a file directly unter "C:\", which is not possible for normal users. So the xlswriter has to be run using administrative privileges.

**Comment by jmcnamara** [comment]
xlsxwriter.lua is no longer maintained.


> On Windows, starting with Win Vista, we found a privilege problem. Packager:_add_to_zip() uses the function "io.tmpfile()", which, in turn, uses the C-runtime function "tmpfile()".

Yes. That is an issue that can occur with the Perl/Python/C versions of this library as well. In those others there is an option to change the location of the tmp dir that the library used. However, I don't think that was an option with io.tmpfile(), at least not when I wrote the code.

If you can find a workaround that works on windows you can replace io.tmpfile() in the source code. It is only used in 2 places.
