### ISSUE TITLE
Vertical alignment does not work.

### ISSUE THREAD

**Issue by moteus** [jmcnamara/xlsxwriter.lua#9]
I test `merge1.lua` and I get vertical alignment as `bottom` not `vcenter`.
I also try set `valign = "center"` result is same.

**Comment by jmcnamara** [comment]
Hi Alexey,

Can you add a small example that demonstrates the issue.

Regards,

John

**Comment by moteus** [comment]
I just run `merge1.lua` from `examples` directory.

**Comment by moteus** [comment]
Tested with current master.

**Comment by moteus** [comment]
Does not work `valign` properties.
to set vertical alignmet nedd to use `merge_format:set_align("vcenter")`
May be just remove `valign` and allaw use array to set align in ctor
```Lua 
merge_format = workbook:add_format{
    align    = {"center","vcenter"}
}
```

**Comment by jmcnamara** [comment]
Hi Alexey,

Thanks for the report. Yes, there is a bug there. I'll fix it and let you know.

John

**Comment by jmcnamara** [comment]
I pushed a fix for this issue. Thanks for the report.
